<a href="https://colab.research.google.com/github/mrzResearchArena/Anticancer-Peptides-CNN/blob/master/Codes/2D-1D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
ls

drive/  sample_data/


In [4]:
cd 'drive/My Drive/ACP-PyFeat'

/content/drive/My Drive/ACP-PyFeat


In [5]:
ls

acp164.txt       blosum-164.npy      bpf-val-194.npy
acp240.txt       blosum-240.npy      dataset-details.txt
acp500.txt       blosum-500.npy      main-AntiCP.h5
acp740.txt       blosum-740.npy      main-train.fa
alter-AntiCP.h5  blosum-in-689.npy   main-val-172.fa
alt-train.fa     blosum-in-776.npy   model-240.png
alt-val-194.fa   blosum-val-172.npy  model-240-single-head.png
bit-in-689.npy   blosum-val-194.npy  model-500-164.png
bit-in-776.npy   bpf-164.npy         model-740.png
bits-164.npy     bpf-240.npy         model-740-single-head.png
bits-240.npy     bpf-500.npy         model-single-Head-500-164.png
bits-500.npy     bpf-740.npy         ROC-240.png
bits-740.npy     bpf-in-689.npy      ROC-500-164.png
bit-val-172.npy  bpf-in-776.npy      ROC-740.png
bit-val-194.npy  bpf-val-172.npy     ROC.png


In [6]:
d740bpf   = np.load('bpf-740.npy')
d740bit   = np.load('bits-740.npy')
d740blo62 = np.load('blosum-740.npy')

d240bpf   = np.load('bpf-240.npy')
d240bit   = np.load('bits-240.npy')
d240blo62 = np.load('blosum-240.npy')

d500bpf   = np.load('bpf-500.npy')
d500bit   = np.load('bits-500.npy')
d500blo62 = np.load('blosum-500.npy')

d164bpf   = np.load('bpf-164.npy')
d164bit   = np.load('bits-164.npy')
d164blo62 = np.load('blosum-164.npy')

In [7]:
d740bit.shape

(740, 25, 31)

In [8]:
print(d740bpf.shape)
print(d740bit.shape)
print(d740blo62.shape)

print(d240bpf.shape)
print(d240bit.shape)
print(d240blo62.shape)

print(d500bpf.shape)
print(d500bit.shape)
print(d500blo62.shape)

print(d164bpf.shape)
print(d164bit.shape)
print(d164blo62.shape)

(740, 25, 20)
(740, 25, 31)
(740, 25, 20)
(240, 25, 20)
(240, 25, 31)
(240, 25, 20)
(500, 25, 20)
(500, 25, 31)
(500, 25, 20)
(164, 25, 20)
(164, 25, 31)
(164, 25, 20)


In [9]:
A = np.array([
    [ 1,  2,  3],
    [11, 22, 33]
])
print(A)

A = A.flatten()
print(A)

[[ 1  2  3]
 [11 22 33]]
[ 1  2  3 11 22 33]


In [10]:
def convert2D1D(D):
    A = []
    for d in D:
        A.append(d.flatten())
    #end-for
    return np.array(A)
#end-def

In [11]:
d740bpf = convert2D1D(d740bpf)
d740bit = convert2D1D(d740bit)
d740blo62 = convert2D1D(d740blo62)

d240bpf = convert2D1D(d240bpf)
d240bit = convert2D1D(d240bit)
d240blo62 = convert2D1D(d240blo62)

d500bpf = convert2D1D(d500bpf)
d500bit = convert2D1D(d500bit)
d500blo62 = convert2D1D(d500blo62)

d164bpf = convert2D1D(d164bpf)
d164bit = convert2D1D(d164bit)
d164blo62 = convert2D1D(d164blo62)

In [12]:
print(d740bpf.shape)
print(d740bit.shape)
print(d740blo62.shape)

print(d240bpf.shape)
print(d240bit.shape)
print(d240blo62.shape)

print(d500bpf.shape)
print(d500bit.shape)
print(d500blo62.shape)

print(d164bpf.shape)
print(d164bit.shape)
print(d164blo62.shape)

(740, 500)
(740, 775)
(740, 500)
(240, 500)
(240, 775)
(240, 500)
(500, 500)
(500, 775)
(500, 500)
(164, 500)
(164, 775)
(164, 500)


In [13]:
d740y  = [1 for _ in range(376)]
d740y += [0 for _ in range(364)]
d740y  = np.array(d740y)


d240y  = [1 for _ in range(129)]
d240y += [0 for _ in range(111)]
d240y  = np.array(d240y)


d500ytrain  = [0 for _ in range(250)]
d500ytrain += [1 for _ in range(250)]
d500ytrain  = np.array(d500ytrain)


d164ytest  = [0 for _ in range(82)]
d164ytest += [1 for _ in range(82)]
d164ytest  = np.array(d164ytest)

In [14]:
# Convert into TF-IDF
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer


def TFIDF(D):
    tfidf = TfidfTransformer(norm='l2').fit(D)

    return np.array(tfidf.transform(D).todense())
#end-def

In [15]:
b = TFIDF(d740bit)

In [16]:
b.shape

(740, 775)

In [17]:
b

array([[0.        , 0.        , 0.        , ..., 0.07429004, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.0853151 ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [18]:
import xgboost as xgb
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier, \
     RandomForestClassifier, \
     AdaBoostClassifier, \
     GradientBoostingClassifier, \
     ExtraTreesClassifier

from sklearn.metrics import accuracy_score, \
     log_loss, \
     classification_report, \
     confusion_matrix, \
     roc_auc_score,\
     average_precision_score,\
     auc,\
     roc_curve, f1_score, recall_score, matthews_corrcoef, auc
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, MinMaxScaler

cv = StratifiedKFold(n_splits=5, shuffle=True)

Names = ['SVM', 'RF', 'ET', 'XGB', 'KNN', 'DT', 'NB', 'AB']
Classifiers = [
    SVC(probability=True),                  #1
    RandomForestClassifier(),               #2
    ExtraTreesClassifier(),                 #3
    xgb.XGBClassifier(),                    #4
    KNeighborsClassifier(n_neighbors=5),    #5
    DecisionTreeClassifier(),               #6
    GaussianNB(),                           #7    
    AdaBoostClassifier(),                   #8
]

In [19]:
def classifiersCV(X, y):
    Results = []
    for classifier, name in zip(Classifiers, Names):
        accuray = []
        auROC = []
        avePrecision = []
        F1_Score = []
        AUC = []
        MCC = []
        Recall = []
        LogLoss = []

        mean_TPR = 0.0
        mean_FPR = np.linspace(0, 1, 100)

        CM = np.array([
            [0, 0],
            [0, 0],
        ], dtype=int)

        # print('{} is done.'.format(classifier.__class__.__name__))
        print(classifier.__class__.__name__+'\n')

        model = classifier
        for (train_index, test_index) in cv.split(X, y):

            X_train = X[train_index]
            X_test = X[test_index]

            y_train = y[train_index]
            y_test = y[test_index]

            # Step 06 : Scaling the feature
            
            scale = StandardScaler()
            X_train = scale.fit_transform(X_train)
            X_test = scale.transform(X_test)

            # model = BaggingClassifier(classifier)
            model.fit(X_train, y_train)

            # print(model.predict(X_train))

            # Calculate ROC Curve and Area the Curve
            y_proba = model.predict_proba(X_test)[:, 1]
            FPR, TPR, _ = roc_curve(y_test, y_proba)
            mean_TPR += np.interp(mean_FPR, FPR, TPR)
            mean_TPR[0] = 0.0
            roc_auc = auc(FPR, TPR)
            ##########################################
            # print(FPR)
            # print(TPR)
            ##########################################

            y_artificial = model.predict(X_test)

            auROC.append(roc_auc_score(y_true=y_test, y_score=y_proba))

            accuray.append(accuracy_score(y_pred=y_artificial, y_true=y_test))
            avePrecision.append(average_precision_score(y_true=y_test, y_score=y_proba)) # auPR
            F1_Score.append(f1_score(y_true=y_test, y_pred=y_artificial))
            MCC.append(matthews_corrcoef(y_true=y_test, y_pred=y_artificial))
            Recall.append(recall_score(y_true=y_test, y_pred=y_artificial))
            AUC.append(roc_auc)

            CM += confusion_matrix(y_pred=y_artificial, y_true=y_test)

        accuray = [_*100.0 for _ in accuray]
        Results.append(accuray)

        mean_TPR /= cv.get_n_splits(X, y)
        mean_TPR[-1] = 1.0
        mean_auc = auc(mean_FPR, mean_TPR)

        print('Accuracy: {0:.2f}'.format(np.mean(Results)))
        # print('auROC: {0:.6f}'.format(np.mean(auROC)))
        # print('auROC: {0:.4f}\n'.format(mean_auc))
        # F.write('AUC: {0:.4f}\n'.format( np.mean(AUC)))
        # print('auPR: {0:.4f}'.format(np.mean(avePrecision))) # average_Precision
        # print('F1_Score: {0:.4f}\n'.format(np.mean(F1_Score)))
        

        TN, FP, FN, TP = CM.ravel()
        # print('Recall: {0:.4f}\n'.format( np.mean(Recall)) )
        print('Sensitivity: {0:.2f}'.format( ((TP) / (TP + FN))*100.0 ))
        print('Specificity: {0:.2f}'.format( ((TN) / (TN + FP))*100.0 ))
        print('MCC: {0:.2f}'.format(np.mean(MCC)))
        # print('Confusion Matrix:\n')
        # print(str(CM)+'\n')

        print('{:.2f} {:.2f} {:.2f} {:.2f}'.format(np.mean(Results), ((TP) / (TP + FN))*100.0, ((TN) / (TN + FP))*100.0, np.mean(MCC)))
        print('_______________________________________'+'\n')
#end-def

In [25]:
X = d240bpf
Y = d240y

classifiersCV(X, Y)

SVC

Accuracy: 70.00
Sensitivity: 62.02
Specificity: 79.28
MCC: 0.42
70.00 62.02 79.28 0.42
_______________________________________

RandomForestClassifier

Accuracy: 73.96
Sensitivity: 79.07
Specificity: 76.58
MCC: 0.56
73.96 79.07 76.58 0.56
_______________________________________

ExtraTreesClassifier

Accuracy: 73.61
Sensitivity: 73.64
Specificity: 72.07
MCC: 0.46
73.61 73.64 72.07 0.46
_______________________________________

XGBClassifier

Accuracy: 75.21
Sensitivity: 78.29
Specificity: 81.98
MCC: 0.60
75.21 78.29 81.98 0.60
_______________________________________

KNeighborsClassifier

Accuracy: 71.25
Sensitivity: 98.45
Specificity: 5.41
MCC: 0.06
71.25 98.45 5.41 0.06
_______________________________________

DecisionTreeClassifier



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:900: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:900: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)


Accuracy: 72.99
Sensitivity: 80.62
Specificity: 82.88
MCC: 0.64
72.99 80.62 82.88 0.64
_______________________________________

GaussianNB

Accuracy: 72.44
Sensitivity: 75.97
Specificity: 61.26
MCC: 0.38
72.44 75.97 61.26 0.38
_______________________________________

AdaBoostClassifier

Accuracy: 72.86
Sensitivity: 78.29
Specificity: 72.97
MCC: 0.52
72.86 78.29 72.97 0.52
_______________________________________



In [36]:
def classifiersTT(X_train, y_train, X_test, y_test):
    for classifier, name in zip(Classifiers, Names):
        
        CM = np.array([
            [0, 0],
            [0, 0],
        ], dtype=int)

        # print('{} is done.'.format(classifier.__class__.__name__))
        print(classifier.__class__.__name__+'\n')

        model = classifier
        # Step 06 : Scaling the feature
        
        scale = StandardScaler()
        X_train = scale.fit_transform(X_train)
        X_test = scale.transform(X_test)

        # model = BaggingClassifier(classifier)
        model.fit(X_train, y_train)

        # print(model.predict(X_train))

        # Calculate ROC Curve and Area the Curve
        y_proba = model.predict_proba(X_test)[:, 1]
        FPR, TPR, _ = roc_curve(y_test, y_proba)
        # mean_TPR += np.interp(mean_FPR, FPR, TPR)
        # mean_TPR[0] = 0.0
        roc_auc = auc(FPR, TPR)
        ##########################################
        # print(FPR)
        # print(TPR)
        ##########################################

        y_artificial = model.predict(X_test)

        auROC = roc_auc_score(y_true=y_test, y_score=y_proba)

        accuracy = accuracy_score(y_pred=y_artificial, y_true=y_test)
        
        MCC = matthews_corrcoef(y_true=y_test, y_pred=y_artificial)

        CM = confusion_matrix(y_pred=y_artificial, y_true=y_test)

        print('Accuracy: {0:.2f}'.format(accuracy))
        # print('auROC: {0:.6f}'.format(np.mean(auROC)))
        # print('auROC: {0:.4f}\n'.format(mean_auc))
        # F.write('AUC: {0:.4f}\n'.format( np.mean(AUC)))
        # print('auPR: {0:.4f}'.format(np.mean(avePrecision))) # average_Precision
        # print('F1_Score: {0:.4f}\n'.format(np.mean(F1_Score)))
        

        TN, FP, FN, TP = CM.ravel()
        # print('Recall: {0:.4f}\n'.format( np.mean(Recall)) )
        print('Sensitivity: {0:.2f}'.format( ((TP) / (TP + FN))*100.0 ))
        print('Specificity: {0:.2f}'.format( ((TN) / (TN + FP))*100.0 ))
        print('MCC: {0:.2f}'.format(MCC))
        # print('Confusion Matrix:\n')
        # print(str(CM)+'\n')
        print('{:.2f} {:.2f} {:.2f} {:.2f}'.format(accuracy*100, ((TP) / (TP + FN))*100.0, ((TN) / (TN + FP))*100.0, MCC))
        print('_______________________________________'+'\n')
#end-def

In [42]:
Xtrain = d500blo62
Ytrain = d500ytrain

Xtest = d164blo62
Ytest = d164ytest

classifiersTT(Xtrain, Ytrain, Xtest, Ytest)

SVC

Accuracy: 0.78
Sensitivity: 82.93
Specificity: 73.17
MCC: 0.56
78.05 82.93 73.17 0.56
_______________________________________

RandomForestClassifier

Accuracy: 0.85
Sensitivity: 86.59
Specificity: 84.15
MCC: 0.71
85.37 86.59 84.15 0.71
_______________________________________

ExtraTreesClassifier

Accuracy: 0.85
Sensitivity: 84.15
Specificity: 85.37
MCC: 0.70
84.76 84.15 85.37 0.70
_______________________________________

XGBClassifier

Accuracy: 0.83
Sensitivity: 84.15
Specificity: 81.71
MCC: 0.66
82.93 84.15 81.71 0.66
_______________________________________

KNeighborsClassifier

Accuracy: 0.67
Sensitivity: 45.12
Specificity: 89.02
MCC: 0.38
67.07 45.12 89.02 0.38
_______________________________________

DecisionTreeClassifier

Accuracy: 0.82
Sensitivity: 80.49
Specificity: 82.93
MCC: 0.63
81.71 80.49 82.93 0.63
_______________________________________

GaussianNB

Accuracy: 0.69
Sensitivity: 69.51
Specificity: 68.29
MCC: 0.38
68.90 69.51 68.29 0.38
____________________________